name: Release

on:
  push:
    branches:
      - dev
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx --package @semantic-release/commit-analyzer --package @semantic-release/git --package @semantic-release/npm semantic-release

  sync-branches:
    needs: release
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && needs.release.result == 'success'

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge main into dev
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin main dev --tags

          git checkout -B dev origin/dev
          git merge origin/main --no-edit
          git push origin dev
